/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT6752. Copyright MediaTek Inc. (C) 2013.
 * Wed Aug 31 21:45:07 2016
 * Do Not Modify the File.
 */

#ifndef __CUST_EINTH
#define __CUST_EINTH

#ifdef __cplusplus
extern "C" {
#endif

#define CUST_EINTF_TRIGGER_RISING     			1    //High Polarity and Edge Sensitive
#define CUST_EINTF_TRIGGER_FALLING    			2    //Low Polarity and Edge Sensitive
#define CUST_EINTF_TRIGGER_HIGH      				4    //High Polarity and Level Sensitive
#define CUST_EINTF_TRIGGER_LOW       				8    //Low Polarity and Level Sensitive

#define CUST_EINT_DEBOUNCE_DISABLE          0
#define CUST_EINT_DEBOUNCE_ENABLE           1

//////////////////////////////////////////////////////////////////////////////


#define CUST_EINT_ACCDET_NUM              1
#define CUST_EINT_ACCDET_DEBOUNCE_CN      256
#define CUST_EINT_ACCDET_TYPE							CUST_EINTF_TRIGGER_LOW
#define CUST_EINT_ACCDET_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_ENABLE

#define CUST_EINT_TOUCH_PANEL_NUM              10
#define CUST_EINT_TOUCH_PANEL_DEBOUNCE_CN      0
#define CUST_EINT_TOUCH_PANEL_TYPE							CUST_EINTF_TRIGGER_FALLING
#define CUST_EINT_TOUCH_PANEL_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE

#define CUST_EINT_ALS_NUM              11
#define CUST_EINT_ALS_DEBOUNCE_CN      0
#define CUST_EINT_ALS_TYPE							CUST_EINTF_TRIGGER_LOW
#define CUST_EINT_ALS_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE

#define CUST_EINT_EXT_BUCK_OC_NUM              12
#define CUST_EINT_EXT_BUCK_OC_DEBOUNCE_CN      0
#define CUST_EINT_EXT_BUCK_OC_TYPE							CUST_EINTF_TRIGGER_HIGH
#define CUST_EINT_EXT_BUCK_OC_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE

#define CUST_EINT_MHALL_NUM              22
#define CUST_EINT_MHALL_DEBOUNCE_CN      0
#define CUST_EINT_MHALL_TYPE							CUST_EINTF_TRIGGER_LOW
#define CUST_EINT_MHALL_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE

#define CUST_EINT_NXP_SMARTPA_EINT_NUM              43
#define CUST_EINT_NXP_SMARTPA_EINT_DEBOUNCE_CN      0
#define CUST_EINT_NXP_SMARTPA_EINT_TYPE							CUST_EINTF_TRIGGER_LOW
#define CUST_EINT_NXP_SMARTPA_EINT_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE

#define CUST_EINT_LENOVO_PIEZO_EINT_NUM              46
#define CUST_EINT_LENOVO_PIEZO_EINT_DEBOUNCE_CN      256
#define CUST_EINT_LENOVO_PIEZO_EINT_TYPE							CUST_EINTF_TRIGGER_LOW
#define CUST_EINT_LENOVO_PIEZO_EINT_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_ENABLE



//////////////////////////////////////////////////////////////////////////////
#ifdef __cplusplus
}

#endif
#endif //_CUST_EINT_H


