/*
 * Generated by MTK SP DrvGen Version 03.13.6  for MT6752. Copyright MediaTek Inc. (C) 2013.
 * Tue Oct 25 17:44:43 2016
 * Do Not Modify the File.
 */

#define CUST_EINT_POLARITY_LOW              0
#define CUST_EINT_POLARITY_HIGH             1
#define CUST_EINT_EDGE_SENSITIVE            0
#define CUST_EINT_LEVEL_SENSITIVE           1




#define CUST_EINT_MD2_CNT      0


